// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: pkg/proto/linkpb/link_service.proto

package linkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterOSDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addr  string `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	OsdId int64  `protobuf:"varint,2,opt,name=osd_id,json=osdId,proto3" json:"osd_id,omitempty"`
}

func (x *RegisterOSDRequest) Reset() {
	*x = RegisterOSDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_linkpb_link_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterOSDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOSDRequest) ProtoMessage() {}

func (x *RegisterOSDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_linkpb_link_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOSDRequest.ProtoReflect.Descriptor instead.
func (*RegisterOSDRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_linkpb_link_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterOSDRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RegisterOSDRequest) GetOsdId() int64 {
	if x != nil {
		return x.OsdId
	}
	return 0
}

type RegisterOSDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *RegisterOSDReply) Reset() {
	*x = RegisterOSDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_proto_linkpb_link_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterOSDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOSDReply) ProtoMessage() {}

func (x *RegisterOSDReply) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_linkpb_link_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOSDReply.ProtoReflect.Descriptor instead.
func (*RegisterOSDReply) Descriptor() ([]byte, []int) {
	return file_pkg_proto_linkpb_link_service_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOSDReply) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_pkg_proto_linkpb_link_service_proto protoreflect.FileDescriptor

var file_pkg_proto_linkpb_link_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b,
	0x70, 0x62, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x69, 0x6e, 0x6b, 0x70, 0x62, 0x22, 0x3f, 0x0a,
	0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x53, 0x44, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x15, 0x0a, 0x06, 0x6f, 0x73, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6f, 0x73, 0x64, 0x49, 0x64, 0x22, 0x2a,
	0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x53, 0x44, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x54, 0x0a, 0x0b, 0x4c, 0x69,
	0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0b, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x53, 0x44, 0x12, 0x1a, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x53, 0x44, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6c, 0x69, 0x6e, 0x6b, 0x70, 0x62, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x4f, 0x53, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x1a, 0x5a, 0x18, 0x6c, 0x69, 0x6e, 0x6b, 0x73, 0x76, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_proto_linkpb_link_service_proto_rawDescOnce sync.Once
	file_pkg_proto_linkpb_link_service_proto_rawDescData = file_pkg_proto_linkpb_link_service_proto_rawDesc
)

func file_pkg_proto_linkpb_link_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_linkpb_link_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_linkpb_link_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_linkpb_link_service_proto_rawDescData)
	})
	return file_pkg_proto_linkpb_link_service_proto_rawDescData
}

var file_pkg_proto_linkpb_link_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_linkpb_link_service_proto_goTypes = []interface{}{
	(*RegisterOSDRequest)(nil), // 0: linkpb.RegisterOSDRequest
	(*RegisterOSDReply)(nil),   // 1: linkpb.RegisterOSDReply
}
var file_pkg_proto_linkpb_link_service_proto_depIdxs = []int32{
	0, // 0: linkpb.LinkService.RegisterOSD:input_type -> linkpb.RegisterOSDRequest
	1, // 1: linkpb.LinkService.RegisterOSD:output_type -> linkpb.RegisterOSDReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_linkpb_link_service_proto_init() }
func file_pkg_proto_linkpb_link_service_proto_init() {
	if File_pkg_proto_linkpb_link_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_proto_linkpb_link_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterOSDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_proto_linkpb_link_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterOSDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_linkpb_link_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_linkpb_link_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_linkpb_link_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_linkpb_link_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_linkpb_link_service_proto = out.File
	file_pkg_proto_linkpb_link_service_proto_rawDesc = nil
	file_pkg_proto_linkpb_link_service_proto_goTypes = nil
	file_pkg_proto_linkpb_link_service_proto_depIdxs = nil
}
